### ISSUE TITLE
Debug Cursor Lag

### ISSUE THREAD

**Issue by majg0** [aevyrie/bevy_mod_raycast#14]
Hi!

In 0.2.2 it seems like no matter what I do, the debug cursor stays one frame after my camera update.

![lag](https://user-images.githubusercontent.com/3044707/121583051-138a3e00-ca30-11eb-99d5-f92179dd4d95.gif)

My code is virtually identical to your example - though I noted you changed from PostUpdate to PreUpdate on master. Neither works for me, and I tried running my transform-updating before and after respectively..

Could this be related to that it should be PreUpdate?

Thankful for a fix!

Great lib! Cheers! <3

**Comment by aevyrie** [comment]
Hey, thanks for the report!

Does the mouse picking example in this repo exhibit the same lag for you? It's hard to tell from the video, but is the lag only with camera movement, or mouse movement alone too?

This looks like a system ordering issue. My suspicion is that your camera update is happening after the raycast is computed.

Could you try dropping in the bevy_mod_picking plugin to see if that changes the behavior? See the minimal example here: https://github.com/aevyrie/bevy_mod_picking/blob/master/examples/3d_scene.rs

All you need to do is drop in the `DefaultPickingPlugins` and `DebugCursorPickingPlugin`, mark pickable entities with the `.insert_bundle(PickableBundle::default());` component, and mark your camera with the `.insert_bundle(PickingCameraBundle::default());` component.

**Comment by martingronlund** [comment]
Thanks for your answer!

After some struggle with bevy git version mismatches, I managed to run the 0.2.2 example of mouse_picking from this repo.

I added some meshes in the background just to lower the fps so that the phenomenon is visible.

```rust
    for x in 0..100 {
        commands.spawn_bundle(PbrBundle {
            mesh: meshes.add(Mesh::from(shape::Icosphere::default())),
            material: materials.add(Color::rgb(0.0, 1.0, 1.0).into()),
            transform: Transform::from_translation(Vec3::new(
                (x % 16) as f32,
                (x / 16) as f32,
                -10.0,
            )),
            ..Default::default()
        });
    }
```

![lag2](https://user-images.githubusercontent.com/3044707/121647000-30f1f300-ca96-11eb-8bb0-41a063a00a48.gif)

I'll go try bevy_mod_picking as well.

**Comment by martingronlund** [comment]
Btw, I'm not sure because I didn't think hard about it, but my gut tells me it could be a source of error to compare with the OS mouse position, as its update frequency is decoupled. Any time the OS mouse updates faster, there should be lag, right?

I think the camera demo is probably the only way to check whether we're doing things correctly or not, right?

I agree it sounds like a system order issue.

I'd imagine the correct order to be.
1. Mouse move
2. Cam move
3. Raycast
4. Draw

Any idea on how to check that?

**Comment by martingronlund** [comment]
Something interesting that I noticed now is that the 3d_scene example of bevy_mod_picking also exhibits noticable cursor lag for me - but when I try to record it (using OBS), in the recording the mouse coincides better with the debug cursor, which to me suggests that this is either a general problem of application lag on my machine rather than a library issue (or OBS has the same problem, but I would be surprised if this was the case). What do you think?

**Comment by martingronlund** [comment]
At last, I tried using bevy_mod_picking instead in the very way that you suggested and my cursor still lags behind in the same way as in my first gif.

If you would like to debug this yourself, I think one easy way to go about it is adding some meshes to lower your FPS so that it's clearly visible (see example code above), and using the following code as a system for cam move.

```rust
fn player_cam_movement(
    keyboard_input: Res<Input<KeyCode>>,
    mut query: Query<(&mut Transform, &Camera)>,
) {
    for (key, dir) in [
        (KeyCode::Left, Vec3::new(-1.0, 0.0, 0.0)),
        (KeyCode::Down, Vec3::new(0.0, 0.0, 1.0)),
        (KeyCode::Right, Vec3::new(1.0, 0.0, 0.0)),
        (KeyCode::Up, Vec3::new(0.0, 0.0, -1.0)),
    ] {
        if keyboard_input.pressed(key) {
            for (mut transform, _) in query.iter_mut() {
                transform.translation = transform.translation + dir;
            }
        }
    }
}
```

**Comment by aevyrie** [comment]
I'll take a more in-depth look into this, but wanted to make a few quick comments:

- This issue is very important to me, reducing latency has been a priority from the beginning. It can never be perfect due to the nature of how the OS hardware cursor and the rendered application output work.
- This is very much tied to framerate and vsync. I'd recommend turning vsync off if latency is important, and targeting 60+ fps will really help. Sounds like you're already doing this. 😄 
- The biggest "bug" would be if there is a 1+ frames of delay. If we can keep the latency to within a single frame, that will at least get us in the ballpark of reaching the best that is possible.
- The challenge with ordering is that to reduce latency, we would want to query the cursor position near the end of the frame, then raycast into the scene. However, you often times want to use the output of that raycast to determine what to update in the scene! If we wait until the end of the frame to get the cursor and raycast, we won't be able to update onscreen objects until next frame, which is probably even worse. This is why I moved updates in mod_picking to the PreUpdate stage. I'm also fairly certain that it doesn't matter when in the frame you grab the mouse events - we can't get new winit events during the frame - so grabbing mouse position at the end of the frame won't even help us here (yet).

I think the most reasonable target will be to ensure latency is always <1 frame (16ms @ 60hz). You will probably also want to avoid anything that directly follows the cursor because it will accentuate any lag. If you try the mod_picking examples without the cursor, you'll probably notice that highlighting feels pretty much instantaneous when you don't have the debug cursor around.

**Comment by aevyrie** [comment]
Based on your earlier comments and some latency/framepacing work I've done, this is almost certainly a vsync and/or system ordering issue. With my `bevy_framepace` plugin, I have next to zero input latency even with vsync on.
