### ISSUE TITLE
Error spam when using with `RapierDebugRenderPlugin`

### ISSUE THREAD

**Issue by LiamGallagher737** [aevyrie/bevy_mod_raycast#70]
I am using the latest commit of the [`bevy_editor_pls`](https://github.com/jakobhellermann/bevy_editor_pls/commit/4c4bd7da11627e1ae4e6c9649b01205791561995) crate. When I add bevy_rapier's `RapierDebugRenderPlugin` to my app my console gets spammed with the following error.

```sh
ERROR raycast: bevy_mod_raycast: Invalid intersection check: `TriangleList` is the only supported `PrimitiveTopology`
```

I understand the bevy_rapier's debug lines aren't using triangle lists but why does it have to spam the console, can't it just skip it?

**Comment by aevyrie** [comment]
This is happening because an entity is marked as a raycast target, but it does not have a supported mesh to raycast against. The solution would be to remove the raycast components (`RaycastMesh::<MyRaycastSet>`) from entities that should not have them. Maybe this is an upstream issue with bevy_editor_pls?

**Comment by LiamGallagher737** [comment]
The issue only happens when using bevy_rapier's debug lines which I highly doubt would have that component.

**Comment by aevyrie** [comment]
The filter here ensures that only entities with that component can be raycasted against: https://github.com/aevyrie/bevy_mod_raycast/blob/193cf2a58f594fa0ec5ff14ed5aa6d3af532967f/src/system_param.rs#L72
